/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'lehel' at '12/23/16 2:27 PM' with Gradle 2.14
 *
 * @author lehel, @date 12/23/16 2:27 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
