/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'lehel' at '12/23/16 2:27 PM' with Gradle 2.14
 *
 * @author lehel, @date 12/23/16 2:27 PM
 */

import org.junit.runner.RunWith
import org.scalatest.{BeforeAndAfter, FunSuite}
import org.scalatest.junit.JUnitRunner
import Database._

@RunWith(classOf[JUnitRunner])
class DatabaseSuite extends FunSuite with BeforeAndAfter {

  val user = UserDTO("user1", "password")
  val userWrongPassword = UserDTO("user1", "password1")

  before {
    init()
  }

  test("database creation") {
    assert(getAllUsers().size == 0)
  }

  test("insert user") {
    insertUser(user)
    assert(getAllUsers().size == 1)
  }

  test("find user") {
    assert(findUser(user.name) == None)
    insertUser(user)
    assert(findUser(user.name).isDefined)
  }

}

