/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'lehel' at '12/23/16 2:27 PM' with Gradle 2.14
 *
 * @author lehel, @date 12/23/16 2:27 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
